### ISSUE TITLE
Caching for Richie (and the sandbox as an example)

### ISSUE THREAD

**Issue by mbenadda** [openfun/richie#1013]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Richie is meant to enable users to build full-featured "marketing" sites and course discovery around online education content.
This means it's supposed to power the very front of the websites that use it, with heavy load. It needs to be able to perform under heavy load.

At the same time, we want to log users in to enable interactions with LMSes behind Richie, and let them access their account or other views specific to them.

**Describe the solution you'd like**
We need to enable caching. We can add a standard Django cache background, and enable page caching. This should cover it for anonymous users.

However, Django-CMS does not cache pages for authenticated users ([does not set cache](https://github.com/divio/django-cms/blob/develop/cms/cache/page.py#L38), [does not use cache](https://github.com/divio/django-cms/blob/a4d49051ff3299d7b1345f8cf26c24a0a9b66a84/cms/views.py#L48)). As a lot of end-users on Richie powered websites will be authenticated, this is a problem.

We need to develop a caching strategy for authenticated users. Either by overriding some of Django-CMS' behaviors or by using sub-page caching.

- [ ] enable regular django caching for anonymous users in the sandbox;
- [ ] enable caching for authenticated users;

**Describe alternatives you've considered**
N/A

**Discovery, Documentation, Adoption, Migration Strategy**
Once we're done, this might warrant a mention in the docs.

**Do you want to work on it through a Pull Request?**
 👍

**Comment by madmatah** [comment]
The following actions have been taken :

### Concerning anonymous users : 

- Regular django caching has been enabled in the sandbox
- Sessions are stored in cache in the sandbox
- All cache related options can be configured with environment variables in the sandbox
- A new component ([SentinelClient](https://github.com/openfun/richie/blob/master/src/richie/apps/core/cache.py)) has been added to richie to be able to use [Redis Sentinel](https://redis.io/topics/sentinel).

### Concerning authenticated users

This is unfortunate but legitimate for Django CMS to disable page cache for authenticated users, since it can lead to security issues or leaking private data to other users. The strategy to adopt really depends on how the website is configured and used. That's why we do not provide anything to handle this case in richie.

In [richie-site-factory](https://github.com/openfun/richie-site-factory/), we decided to monkey patch Django CMS to enable page cache for all non-staff users. This basic approach works because we are serving the same content for all our users. But it might change in the future and we may have to add vary headers.
