### ISSUE TITLE
404 Not Found error when trying to access a Program

### ISSUE THREAD

**Issue by natea** [openfun/richie#1140]
## Bug Report

**Expected behavior/code**
From the Programs page on the demo site, I would expect that when I click on a Program, it would show me the Program page.

**Actual Behavior**
Go to this page (https://demo.richie.education/en/programs/) and click on any of the Programs, and you'll get a 404 error.

**Steps to Reproduce**
1. Go here: https://demo.richie.education/en/programs/
2. Click on a program
3. And then the 404 happens!

**Environment**
- Richie version:
- Platform:

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by sampaccoud** [comment]
Thank you @natea for the report. Can you try again? The site is being reset every night (Paris time) so maybe you fell during the time it is rebuilding? It is done live not atomically for the moment :man_shrugging:

**Comment by natea** [comment]
It's still not working when I have my language set to English, but when I set it to French, then the pages do load:
https://demo.richie.education/fr/parcours/le-droit-de-changer-a-letat-pur/

**Comment by natea** [comment]
This issue appears to have gone away, so I'm closing it.

**Comment by sampaccoud** [comment]
@natea I did not manage to see the bug either but maybe it is due to someone breaking the site while testing it as we give superuser credentials. Another possibility is that the site is reinitialized every night Paris time which is the middle of the west coast afternoon 😅 we will try to find some time to do a dump of the initial database and avoid building the site live.
