### ISSUE TITLE
Show/Hide Main Navigation

### ISSUE THREAD

**Issue by ppshameer** [openfun/richie#1246]
The Show/Hide main Navigation is not working as expected (based on my settings on django admin). 
![image](https://user-images.githubusercontent.com/537741/104808639-a368ea80-57f8-11eb-9587-59f442ddf51d.png)
Selected on 3 menus but getting some other items.
![image](https://user-images.githubusercontent.com/537741/104808661-c72c3080-57f8-11eb-8c62-4c79ba016a4e.png)

Are there any other settings or do I missed something?

Thanks

**Comment by sampaccoud** [comment]
At first I thought it was a bug, then I tested it locally. In fact, your pages "News", "Courses" and "Organizations" are still visible in the menu because you did not republish them. This is actually a feature: deactivating the menu flag is a change that, as other changes to a page, must go through publication before they are visible on the public site.

This does not explain however why "Discover" and "Categories" are not present in the menu :man_shrugging:  Any idea?

**Comment by ppshameer** [comment]
Hi Sam,
Great, "News", "Courses" and "Organizations" are ready after republish.
Still, Discover is not in place., I tried republishing. No changes yet.
Discover is a new page created with template "Search".

Thanks

**Comment by sampaccoud** [comment]
You must have changed something else in the page's settings... Can you create a new page with the same template to see if it appears?

**Comment by ppshameer** [comment]
Hi Sam, 
Fixed, It was a custom css issue.

Thanks for your support.
Shameer P.
