### ISSUE TITLE
Search crash when several languages are selected

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1673]
## Bug Report

**Expected behavior/code**
A user should be able to search courses available in several languages

**Actual Behavior**
If user wants to filter with several languages, the search crash.

**Steps to Reproduce**
1. Go to the search page
2. In the sidebar, in the languages filter pane, select several languages
3. Boom, the search crash

**Environment**
- Richie version: 2.14.0
- Platform: Mac OS

**Possible Solution**
Investigate why elasticsearch returns a 400 Bad request in this case.

**Additional context/screenshots**
```json
{"errors":{"languages":["Select a valid choice. en,ar is not one of the available choices."]}}
```
![2022-04-05 19 11 54](https://user-images.githubusercontent.com/9265241/161812935-89a17b8f-9488-44e6-8cef-ffb8eeb5cc4b.gif)

**Comment by sampaccoud** [comment]
In fact the backend is expecting multiple languages as `/api/v1.0/courses/?languages=fr&languages=en` (see https://github.com/openfun/richie/blob/master/tests/apps/search/test_query_courses_facets.py#L940).

The frontend queries with: `/api/v1.0/courses/?languages=fr,en`

This bug is the first example in Richie of a bug that could only be avoided with e2e tests :man_shrugging:...
