### ISSUE TITLE
Add a plugin to create course plans

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#271]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
We need a plugin to easily build a course plan

**Describe the solution you'd like**
A course plan looks like the screenshot below.
It could also be a more structured index with nested subtitles.
The plugin should allow adding titles by level.

**Describe alternatives you've considered**
Should we allow markdown?

**Discovery, Documentation, Adoption, Migration Strategy**
![image](https://user-images.githubusercontent.com/1427165/42170792-d3174f8c-7e17-11e8-9ada-316a3b85196e.png)

**Comment by sveetch** [comment]
Since we are using CKeditor for many other content, i recommend to avoid using any structured text formatting like ReST or Markdown. It perturbs users and you will have to bring them a lot of help to using it, and finally it will results in problems.

By the way, i don't think you need formatting here, course plan will have to be correctly styled (according to an ergonomic design) and that's all. Having links in course plan will results to nasty user tricks, even bold or italic would be disturbing.

**Comment by sampaccoud** [comment]
A plugin for course plans was added in PR https://github.com/openfun/richie/pull/947.
