### ISSUE TITLE
Adding description to organization

### ISSUE THREAD

**Issue by 2018D** [openfun/richie#299]
## Bug Report

**Expected behavior/code**
On an organization detail page:

- Add text plugin to description placeholder
- Write said description

**Actual Behavior**
Cannot add text plugin to description placeholder. It gives this error message even if placeholder is empty:
"This placeholder already has the maximum number (1) of allowed Text plugins."

**Steps to Reproduce**
1. Create new organization
2. Add text plugin to description placeholder.
3. And then the bug happens!

Alternate:
1. Go on existing factory created organization
2. Delete existing text plugin from description placeholder.
3. Add text plugin to description placeholder.
4. And then the bug happens!

**Environment**
- Richie version: master of 16 july 2018
- Platform: firefox/chrome

**Possible Solution**

**Additional context/Screenshots**
![screenshot_2018-07-16 hernandez rodriguez and sullivan](https://user-images.githubusercontent.com/17911549/42779731-455c1990-890f-11e8-9e3c-f10858323c49.png)

**Comment by sveetch** [comment]
Reproduced the bug here too. It's troubling since banner does not have this erroneous behavior although it's configured the same manner. Tried some quick changes like renaming placeholder to a more specific one or changing some config in CMS_PLACEHOLDER_CONF but it does not fix the bug.

Didn't finded any related bug from DjangoCMS issues, i will try to add some debugging pointer locally to track the problem.

**Comment by sampaccoud** [comment]
It seems to be a recurrent issue in DjangoCMS: https://github.com/divio/django-cms/issues/3736

I confirmed that we are facing orphaned plugins by running the "cms check" command.

The troubling part is that the orphaned plugin appears as soon as you click to add a plugin and before you submit the form to create the plugin... I think the code of the custom TextPlugin that we included in the project is responsible but I didn't figure out where yet.

**Comment by sveetch** [comment]
So temporary orphan plugin is the correct behavior even it brakes attempted behavior with "limits" option in CMS_PLACEHOLDER_CONF.

We will soon create our own simple text plugin which will use Ckeditor widget, with its own ckeditor config and without the djangocms-text-ckeditor code that create temporary orphan. This is required since we absolutely need it to be able to write HTML and have a limit on plugin content.

**Comment by sveetch** [comment]
@2018D your issues should be fixed now since 07d06e9 implement a new simple text plugin which respect contraint from CMS_PLACEHOLDER_CONF.

Please give it an eye to valide and feel free to close this issue. Remember you may need to apply migration coming with the new plugin.

**Comment by 2018D** [comment]
It's working now. I'm closing the issue.
