### ISSUE TITLE
Demo site script should use list template on organizations, persons, subjects pages

### ISSUE THREAD

**Issue by rmoch** [openfun/richie#325]
## Feature Request

We have a generic page template which display a list of child pages: child_page_list.html
We should use this template on pages like organisations, persons or subjects to build a better and easier to understand demo site.

**Comment by sveetch** [comment]
Well it should do a basic render of subjects, organizations, etc.. from their index pages (Subjects, Organizations, etc..), it will be nice to start since for now these pages are empty.

But in futur it may won't fit to attempted layout, since subjects, orgs, etc.. does not have the same content. For getting child pages we could just rely on "menu" templatetag from djangocms.
