### ISSUE TITLE
why can not get the courses、subjects、organzations?

### ISSUE THREAD

**Issue by kylincode** [openfun/richie#378]
when I click the courses in the index, the page show ,but no course、subjects、organzations. like this image（get 500 error）:
![image](https://user-images.githubusercontent.com/15274994/46457838-4d6a0780-c7e6-11e8-9469-f19053a4d252.png)

**Comment by mbenadda** [comment]
Hello @kylincode,

Thanks for your report. We're indeed missing documentation about this. This is somewhat intentional as the Search is one of the parts that still needs some serious work to be done before it can be used by anyone.

### Quick answer

You can get a glimpse of how it looks like and how it works right now. You'll notice the search box and filters need some UX improvements.

**CAVEAT:** it is hardcoded to use demo data pulled directly from our own openedx instance.

Just run `docker-compose exec app python sandbox/manage.py bootstrap_elasticsearch` (with the `app` container running, otherwise replace `exec` with `run --rm` and relaunch the app container).

### Explanation

Richie is built around the idea that course marketing material relevant to a marketing site and a search engine is not the same thing as an actual course on openedx. This is why it has its own models for courses and other objects.

Our search engine uses an API running with ElasticSearch. This means eg. courses need to be indexed into this ElasticSearch instance before you can use the Search view. This is exactly what the command I gave you above does.

Data retrieval for the purpose of indexing is done in individual indexers for each resource that are decoupled from the CLI command and other parts of the Search. The `get_data_for_es` method implements this for each indexer. You can see the one for courses [right there](https://github.com/openfun/richie/blob/master/src/richie/apps/search/indexers/courses.py#L114).

We intend to modify them to get data from the models instead of the remote API they're using now (with the `walk_api_json_list` call). In the meantime, you can get a nice demo with your own data if you modify `get_data_for_es` to get data from your own sources, and just respect the returned objects shape in the existing methods.

---

I hope this answers your questions. Let me know if you're interested in learning more about and working with Richie in the future 👍
