### ISSUE TITLE
Crop images

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie#603]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
Logo and cover images are distorted when the uploaded image is not of the expected ratio (I withnessed it on the organization detail page for example).
On other images, it is the layout that gets distorted (for example the course cover image will disort).
We did not notice it up to now because our demo site is built on images that are already sized as expected.

**Describe the solution you'd like**
- [x] Add images with the wrong ratio in our demo site,
- [x] Fix issue by applying cropping via easy thumbnail.

Example:

<img src='https://user-images.githubusercontent.com/1427165/55559345-4d43b980-56ee-11e9-9df6-6959820e7ca7.png' width="600">

**Comment by sveetch** [comment]
Since previous PR, there is no anymore image exceeding container width when image is too large.

Also there is no more distorted image. And logo in detail page (like your screenshot) there is a soft crop by css rules.

Unfortunaly i'm seeing a problem with plugin image, on these logos given width and height (inside a `{% with .. %}`) is not respected, we ask for 126pixels width but on a test i saw a 640px image.

**Comment by sveetch** [comment]
I just checked code and performed some debug, in fact these context variables 'width' and 'height' are only used to [fill reference dict about size](https://github.com/divio/djangocms-picture/blob/master/djangocms_picture/cms_plugins.py#L71) that is not really used except for `srcset` and `sizes` image attribute (responsive image HTML5 attributes).

And it seems cropping is only performed inside model code, so never these template context variable could affect crop.

**Comment by sveetch** [comment]
After discussion, some reads and tests there seems a way to enforce thumbnailing without to imply any user requirement.

The default PicturePlugin template should include some easy thumbnail usage. But we have another problem that cms plugins don't allow to define a custom path, but instead a key word for a template dir that plugin will search in hardcoded path. 

Since the default is allready hardcoded we cannot make it from settings. The only way is to override template but this is not possible in our current configuration since richie.core.apps is load after cms plugins and the loading strategy with apps is "the first path always win", since the order depends from installed_apps settings, richie can not win against cms plugins.

So, i just tried to change these thing in a demo branch (just a PoC, not intended to be merged). You may try it locally if you want, but at least you just have to know that it works:

https://github.com/openfun/richie/pull/646

- Moving richie.apps.core before cms apps in settings.INSTALLED_APPS does not seems to break anything (well i just tested to navigate full some pages in demo and checked than tests are not broken);
- It results we are able to override default plugin templates (tested with PicturePlugin but it could be used for other ones);
- From our default template, context variables width&height (like we pass around placeholder with `{% with .. %}`) are correctly reachable.

What i don't know yet is how to introduce easy thumbnail usage to enforce size limits with PicturePlugin features.

- Cropping in plugin seems to be applied from model (??) so if user enable cropping, is easy thumbnail will be applied on top of an already cropped image ?
- Responsive option enable seems to create thumbnail and define them in HTML5 attributes "srcset" and "sizes". How can we manage this with easy thumbnail ?

**Comment by sampaccoud** [comment]
This was fixed by PR https://github.com/openfun/richie/pull/680.
