### ISSUE TITLE
Consider re-organizing front-end tree

### ISSUE THREAD

**Issue by jmaupetit** [openfun/richie#74]
## Purpose

The current front-end sources and build targets organization in not obvious. I think we might consider at least discussing design decisions here.

This is a follow-up issue after two conversations that started here:

* https://fun-dev.slack.com/archives/C041R8P6X/p1522331204000342
* https://github.com/openfun/richie/pull/73#pullrequestreview-108117561

## Proposal

1. build targets should be placed in the project main static directory, _e.g._ `richie/static/js` and `richie/static/css`,
2. targets build directories must be added to the project `.gitignore`,
3. front-end sources should stand in a separated directory, _e.g._ `richie/assets/{scss,js}`,
4. **all** SCSS sources should be in the **same** directory, _e.g._ `richie/assets/scss`, each file corresponding to styles for an application's components (_e.g._ `_search.scss` for the `search` application), or a directory (_e.g._ `richie/assets/scss/search/*.scss`) if styles related to an application becomes too big.

```
.
└── richie
    ├── assets
    │   ├── js
    │   └── scss
    │       └── search
    └── static
        ├── css
        ├── images
        └── js
```

**Comment by sveetch** [comment]
For Sass sources it could be better, since some skeleton parts can be very very long and sources for apps can grown larger throughout development and design integration.

I propose to start on something like:

```
└── richie
    ├── assets
    │   ├── js
    │   └── scss
    │       └── components
    │            └── _content.scss
    │            └── _header.scss
    │            └── _footer.scss
    │       └── apps
    │            └── search
    └── static
        ├── css
        ├── images
        └── js
```
Where header and footer components are loaded after every 'apps' sources and finally content component. This way component can inherit from some apps behavior and finally content component can override everything else for user own design needs.

**Comment by mbenadda** [comment]
Right now our philosophy (except for @jmaupetit) is that style files need to live next to the template/component they are styling.

This is because each style file is very tightly coupled to the actual markup. Together they make up the UI. And coupled code that performs a unit of functionality should in our opinion be kept in one place and not peppered over the codebase just because it has a different file extension.

If there are convincing technical reasons to split this code apart, we're open to changing our plans — for Django templates. As for frontend stuff, think it's pretty much admitted at this point that this is the right way to do it.
